# Problem Specification
# 0: SedovPolar, 1: SedovCartesian, 2: Sedov1DCartesian
# 3: NohPolar, 4: NohCartesian, 5: Saltzman
# 6: SodPolar, 7: SodCartesian, 8: TriplePoint
# 9: TwoDimRiemann, 10: TaylorGreen
which_case = 1

# Time Parameters
start_time = 0.0
end_time = 1.0
delta_time = 1e-5

# AMR Parameters
# 0: DensityGradient, 1: PressureGradient, 2: VelocityGradient, 3: Distance
refine_coarsen_enum = 1
minus_level = 4
max_level = 7
refine_err = 1.0
coarsen_error = 0.8
refine_period = 4

# Output Parameters
write_interval_time = 0.1
write_interval_step = 100
